//! Build script: walks the `html/` directory and generates a Rust source file
//! that embeds every static asset (index.html + built JS/CSS/etc.) via
//! `include_bytes!`. The generated file is consumed by `src/server/admin.rs`
//! through `include!(concat!(env!("OUT_DIR"), "/embedded_html.rs"))`.
//!
//! The `html/` directory is the output target of the Vue frontend build
//! (`zorv-ui`), so this keeps the web console fully self-contained in the
//! binary with no runtime file access.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing");
    let html_dir = Path::new(&manifest_dir).join("html");
    println!("cargo:rerun-if-changed=html");

    let mut files: Vec<(String, String)> = Vec::new();
    if html_dir.is_dir() {
        collect_files(&html_dir, "", &mut files);
        files.sort();
    }

    let mut entries = String::new();
    for (rel, abs) in &files {
        // Use raw string literals so Windows backslashes need no escaping.
        entries.push_str(&format!(
            "    (\"{}\", include_bytes!(r#\"{}\"#)),\n",
            rel, abs
        ));
    }

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR missing");
    let generated = format!(
        "// Auto-generated by build.rs. Do not edit.\n\
         pub static FILES: &[(&str, &[u8])] = &[\n{entries}];\n"
    );
    fs::write(Path::new(&out_dir).join("embedded_html.rs"), generated)
        .expect("failed to write embedded_html.rs");
}

fn collect_files(dir: &Path, prefix: &str, out: &mut Vec<(String, String)>) {
    for entry in fs::read_dir(dir).expect("failed to read html dir") {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        let rel = if prefix.is_empty() {
            name.clone()
        } else {
            format!("{prefix}/{name}")
        };
        if path.is_dir() {
            collect_files(&path, &rel, out);
        } else {
            out.push((rel, path.to_string_lossy().into_owned()));
        }
    }
}
