//! Zorv configuration definitions and loading.
//!
//! The server config corresponds to `zorvd.toml`, the client config to `zorv.toml`.
//!
//! All structs derive `serde::Deserialize`; optional fields use `#[serde(default)]`
//! so missing TOML keys fall back to the struct's `Default` implementation.

use serde::{Deserialize, Serialize};

use crate::common::error::{Result, ZorvError};

// ---------------------------------------------------------------------------
// Server configuration (zorvd.toml)
// ---------------------------------------------------------------------------

/// Server root configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerConfig {
    /// Tunnel listen address, e.g. `"0.0.0.0:8443"`.
    pub tunnel_addr: String,
    /// Paths to the TLS certificate and private key.
    pub tls: ServerTlsConfig,
    /// Authentication configuration (shared token + optional IP allowlist).
    pub auth: AuthConfig,
    /// Proxy rule list (optional).
    ///
    /// The server can start without any rules on first deploy; rules can then be
    /// added dynamically from the admin UI and persisted back to the config file.
    #[serde(default)]
    pub proxies: Vec<ProxyConfig>,
    /// Performance tuning parameters; defaults to [`PerformanceConfig::default`].
    #[serde(default)]
    pub performance: PerformanceConfig,
    /// Logging configuration; defaults to [`LogConfig::default`].
    #[serde(default)]
    pub log: LogConfig,
    /// Traffic obfuscation configuration; defaults to [`ObfuscationConfig::default`].
    #[serde(default)]
    pub obfuscation: ObfuscationConfig,
    /// Web admin UI configuration; defaults to [`AdminConfig::default`] (disabled).
    #[serde(default)]
    pub admin: AdminConfig,
    /// Data directory (where persistent files such as traffic stats are stored,
    /// created automatically); defaults to `"data"`.
    #[serde(default = "default_data_dir")]
    pub data_dir: String,
    /// Event notification configuration (e.g. client-offline alert webhook);
    /// disabled by default.
    #[serde(default)]
    pub notify: NotifyConfig,
}

/// Event notification configuration.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NotifyConfig {
    /// Webhook URL for client-offline notifications (http/https, POST JSON
    /// `{"client_id":"...","event":"offline"}`).
    #[serde(default)]
    pub webhook: Option<String>,
}

fn default_data_dir() -> String {
    "data".to_string()
}

/// Server web admin UI configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AdminConfig {
    /// Whether the admin UI is enabled. Defaults to `false`.
    #[serde(default)]
    pub enabled: bool,
    /// Admin UI listen address; defaults to `"127.0.0.1:9000"` (local access only).
    #[serde(default = "default_admin_listen")]
    pub listen: String,
    /// Admin UI login username; defaults to `"admin"`.
    #[serde(default = "default_admin_username")]
    pub username: String,
    /// Admin UI login password. Defaults to an empty string; when empty, **login is
    /// disabled** (requests are let through). Supports plaintext or a
    /// PBKDF2-HMAC-SHA256 hash (`$pbkdf2-sha256$...` prefix, generated by
    /// `zorvd hash-password`).
    #[serde(default)]
    pub password: String,
    /// Optional TLS configuration for the admin UI. When set, the admin UI is
    /// served over HTTPS; defaults to plain HTTP.
    #[serde(default)]
    pub tls: Option<AdminTlsConfig>,
}

/// Admin UI HTTPS configuration (optional).
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AdminTlsConfig {
    pub cert_file: String,
    pub key_file: String,
}

fn default_admin_listen() -> String {
    "127.0.0.1:9000".to_string()
}

fn default_admin_username() -> String {
    "admin".to_string()
}

impl Default for AdminConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            listen: "127.0.0.1:9000".to_string(),
            username: "admin".to_string(),
            password: String::new(),
            tls: None,
        }
    }
}

/// Server TLS configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ServerTlsConfig {
    /// PEM certificate file path.
    pub cert_file: String,
    /// PEM private key file path.
    pub key_file: String,
}

// ---------------------------------------------------------------------------
// Client configuration (zorv.toml)
// ---------------------------------------------------------------------------

/// Client root configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientConfig {
    /// Unique client identifier, used for server-side routing binding.
    pub client_id: String,
    /// Server tunnel address, e.g. `"host:8443"`.
    pub server_addr: String,
    /// Authentication configuration (must match the server token).
    pub auth: AuthConfig,
    /// Client TLS configuration.
    pub tls: ClientTlsConfig,
    /// Client proxy rule list (optional).
    ///
    /// The client no longer needs to declare proxy rules: forwarding targets are
    /// configured on the server admin UI, and the server delivers the target in
    /// the `STREAM_OPEN` frame for the client to connect to the local destination.
    #[serde(default)]
    pub proxies: Vec<ProxyConfig>,
    /// Reconnect parameters; defaults to [`ReconnectConfig::default`].
    #[serde(default)]
    pub reconnect: ReconnectConfig,
    /// Logging configuration; defaults to [`LogConfig::default`].
    #[serde(default)]
    pub log: LogConfig,
    /// Traffic obfuscation configuration; defaults to [`ObfuscationConfig::default`].
    #[serde(default)]
    pub obfuscation: ObfuscationConfig,
}

/// Client TLS configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientTlsConfig {
    /// Whether to verify the server certificate. Defaults to `true`; can be
    /// disabled for self-signed setups (testing only).
    #[serde(default = "default_verify_cert_true")]
    pub verify_cert: bool,
    /// Custom CA file path. Required when `verify_cert=true`.
    #[serde(default)]
    pub ca_file: Option<String>,
}

fn default_verify_cert_true() -> bool {
    true
}

impl Default for ClientTlsConfig {
    fn default() -> Self {
        Self {
            verify_cert: true,
            ca_file: None,
        }
    }
}

/// Reconnect backoff parameters.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReconnectConfig {
    /// Initial backoff delay, e.g. `"2s"`.
    pub initial_delay: String,
    /// Maximum backoff delay, e.g. `"60s"`.
    pub max_delay: String,
    /// Backoff multiplier; each reconnect does `delay *= backoff_factor`.
    pub backoff_factor: f64,
    /// Maximum retry count. `0` means retry forever.
    pub max_retries: u32,
}

impl Default for ReconnectConfig {
    fn default() -> Self {
        Self {
            initial_delay: "2s".to_string(),
            max_delay: "60s".to_string(),
            backoff_factor: 2.0,
            max_retries: 0,
        }
    }
}

// ---------------------------------------------------------------------------
// Shared sub-configurations
// ---------------------------------------------------------------------------

/// Authentication configuration, shared by server and client.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthConfig {
    /// Shared authentication token.
    pub token: String,
    /// Optional IP allowlist (only enforced on the server side).
    #[serde(default)]
    pub allowed_ips: Option<Vec<String>>,
}

/// A single proxy rule.
///
/// - Server side: `listen` (public listen address) and `client_id` (bound client)
///   are required.
/// - Client side: `listen` / `client_id` are optional; `target` (local target
///   address) is required.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ProxyConfig {
    /// Rule name, used for logging and route matching.
    pub name: String,
    /// Proxy type: `"tcp"` or `"udp"`. Written as `type = "tcp"` in TOML.
    #[serde(rename = "type")]
    pub proxy_type: String,
    /// Server public listen address (required on the server side).
    #[serde(default)]
    pub listen: Option<String>,
    /// Bound client ID (required on the server side).
    #[serde(default)]
    pub client_id: Option<String>,
    /// Local target address on the client side, e.g. `"127.0.0.1:22"`.
    pub target: String,
}

/// Performance tuning parameters.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PerformanceConfig {
    /// Maximum concurrent streams per tunnel, default 1024.
    pub max_streams_per_tunnel: usize,
    /// Per-stream buffer size (bytes), default 256KB = 262144.
    pub stream_buffer_size: usize,
    /// Receive buffer size (bytes), default 1MB = 1048576.
    pub recv_buffer_size: usize,
}

impl Default for PerformanceConfig {
    fn default() -> Self {
        Self {
            max_streams_per_tunnel: 1024,
            stream_buffer_size: 262144,
            recv_buffer_size: 1048576,
        }
    }
}

/// Logging configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LogConfig {
    /// Log level, e.g. `"info"` / `"debug"`.
    pub level: String,
    /// Log output target, e.g. `"stdout"` or a file path such as `"./app.log"`.
    pub output: String,
}

impl Default for LogConfig {
    fn default() -> Self {
        Self {
            level: "info".to_string(),
            output: "./app.log".to_string(),
        }
    }
}

/// Traffic obfuscation configuration (Phase 2, corresponds to product.md 3.6/3.7).
///
/// Defaults keep MVP behavior: random padding off, heartbeat jitter on.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ObfuscationConfig {
    /// Whether to enable random padding to flatten packet-length distribution.
    /// Default off (for low-latency scenarios).
    #[serde(default)]
    pub padding: bool,
    /// Maximum random padding bytes per frame, default 255.
    #[serde(default = "default_padding_max")]
    pub padding_max: usize,
    /// Whether to jitter heartbeat intervals. Default on.
    #[serde(default = "default_heartbeat_jitter_true")]
    pub heartbeat_jitter: bool,
}

fn default_padding_max() -> usize {
    255
}

fn default_heartbeat_jitter_true() -> bool {
    true
}

impl Default for ObfuscationConfig {
    fn default() -> Self {
        Self {
            padding: false,
            padding_max: 255,
            heartbeat_jitter: true,
        }
    }
}

// ---------------------------------------------------------------------------
// Loading and helper functions
// ---------------------------------------------------------------------------

/// Load server configuration from a TOML file.
///
/// Both read and parse failures are wrapped as [`ZorvError::Config`].
pub fn load_server(path: &str) -> Result<ServerConfig> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| ZorvError::Config(format!("read config {} failed: {}", path, e)))?;
    toml::from_str(&content)
        .map_err(|e| ZorvError::Config(format!("parse config {} failed: {}", path, e)))
}

/// Serialize the server configuration and write it back to a TOML file (for admin
/// UI persistence).
///
/// Uses `toml::to_string_pretty` to produce readable TOML; the original file is
/// overwritten, losing comments and formatting.
pub fn save_server(path: &str, cfg: &ServerConfig) -> Result<()> {
    let content = toml::to_string_pretty(cfg)
        .map_err(|e| ZorvError::Config(format!("serialize config failed: {}", e)))?;
    std::fs::write(path, content)
        .map_err(|e| ZorvError::Config(format!("write config {} failed: {}", path, e)))
}

/// Load client configuration from a TOML file.
///
/// Both read and parse failures are wrapped as [`ZorvError::Config`].
pub fn load_client(path: &str) -> Result<ClientConfig> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| ZorvError::Config(format!("read config {} failed: {}", path, e)))?;
    toml::from_str(&content)
        .map_err(|e| ZorvError::Config(format!("parse config {} failed: {}", path, e)))
}

/// Parse a duration string into whole seconds.
///
/// Supported formats:
/// - `"2s"` → `2`
/// - `"60s"` → `60`
/// - `"500ms"` → `1` (rounded up: `(500+999)/1000`)
/// - `"10"` (bare number) → `10`
///
/// Returns [`ZorvError::Config`] when the string cannot be parsed.
pub fn parse_duration_secs(s: &str) -> Result<u64> {
    let s = s.trim();
    if let Some(num) = s.strip_suffix("ms") {
        let n: u64 = num
            .parse()
            .map_err(|_| ZorvError::Config(format!("invalid duration: {}", s)))?;
        // Round ms up to whole seconds, so e.g. 500ms does not parse to 0.
        Ok(n.div_ceil(1000))
    } else if let Some(num) = s.strip_suffix('s') {
        let n: u64 = num
            .parse()
            .map_err(|_| ZorvError::Config(format!("invalid duration: {}", s)))?;
        Ok(n)
    } else {
        let n: u64 = s
            .parse()
            .map_err(|_| ZorvError::Config(format!("invalid duration: {}", s)))?;
        Ok(n)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_durations() {
        assert_eq!(parse_duration_secs("2s").unwrap(), 2);
        assert_eq!(parse_duration_secs("60s").unwrap(), 60);
        assert_eq!(parse_duration_secs("500ms").unwrap(), 1);
        assert_eq!(parse_duration_secs("1001ms").unwrap(), 2);
        assert_eq!(parse_duration_secs("10").unwrap(), 10);
        assert!(parse_duration_secs("abc").is_err());
    }

    #[test]
    fn server_config_minimal() {
        let toml = r#"
            tunnel_addr = "0.0.0.0:8443"

            [tls]
            cert_file = "cert.pem"
            key_file = "key.pem"

            [auth]
            token = "secret"

            [[proxies]]
            name = "ssh"
            type = "tcp"
            listen = "0.0.0.0:2222"
            client_id = "client-1"
            target = "127.0.0.1:22"
        "#;
        // Verify field mapping via TOML parsing
        let cfg: ServerConfig = toml::from_str(toml).unwrap();
        assert_eq!(cfg.tunnel_addr, "0.0.0.0:8443");
        assert_eq!(cfg.tls.cert_file, "cert.pem");
        assert_eq!(cfg.auth.token, "secret");
        assert!(cfg.auth.allowed_ips.is_none());
        assert_eq!(cfg.proxies.len(), 1);
        assert_eq!(cfg.proxies[0].proxy_type, "tcp");
        assert_eq!(cfg.proxies[0].target, "127.0.0.1:22");
        // Default fields
        assert_eq!(cfg.performance.max_streams_per_tunnel, 1024);
        assert_eq!(cfg.log.level, "info");
        assert!(!cfg.admin.enabled);
        assert_eq!(cfg.admin.listen, "127.0.0.1:9000");
        assert_eq!(cfg.admin.username, "admin");
        assert!(cfg.admin.password.is_empty());
        assert_eq!(cfg.data_dir, "data");
    }

    #[test]
    fn server_config_without_proxies_parses() {
        // First deploy without [[proxies]] must still parse and start
        let toml = r#"
            tunnel_addr = "0.0.0.0:8443"

            [tls]
            cert_file = "cert.pem"
            key_file = "key.pem"

            [auth]
            token = "secret"
        "#;
        let cfg: ServerConfig = toml::from_str(toml).unwrap();
        assert!(cfg.proxies.is_empty());
        assert_eq!(cfg.data_dir, "data");
    }

    #[test]
    fn save_server_roundtrip() {
        let toml = r#"
            tunnel_addr = "0.0.0.0:8443"

            [tls]
            cert_file = "cert.pem"
            key_file = "key.pem"

            [auth]
            token = "secret"

            [[proxies]]
            name = "ssh"
            type = "tcp"
            listen = "0.0.0.0:2222"
            client_id = "client-1"
            target = "127.0.0.1:22"

            [admin]
            enabled = true
            listen = "0.0.0.0:9000"
        "#;
        let cfg: ServerConfig = toml::from_str(toml).unwrap();
        let out = toml::to_string_pretty(&cfg).unwrap();
        let back: ServerConfig = toml::from_str(&out).unwrap();
        assert_eq!(back.tunnel_addr, cfg.tunnel_addr);
        assert_eq!(back.auth.token, cfg.auth.token);
        assert_eq!(back.proxies.len(), 1);
        assert!(back.admin.enabled);
        assert_eq!(back.admin.listen, "0.0.0.0:9000");
    }

    #[test]
    fn client_config_defaults() {
        let toml = r#"
            client_id = "client-1"
            server_addr = "example.com:8443"

            [auth]
            token = "secret"

            [tls]
            # verify_cert should default to true

            [[proxies]]
            name = "ssh"
            type = "tcp"
            target = "127.0.0.1:22"
        "#;
        let cfg: ClientConfig = toml::from_str(toml).unwrap();
        assert_eq!(cfg.client_id, "client-1");
        assert!(cfg.tls.verify_cert);
        assert!(cfg.tls.ca_file.is_none());
        // reconnect defaults
        assert_eq!(cfg.reconnect.initial_delay, "2s");
        assert_eq!(cfg.reconnect.max_delay, "60s");
        assert_eq!(cfg.reconnect.backoff_factor, 2.0);
        assert_eq!(cfg.reconnect.max_retries, 0);
        // listen / client_id are optional on the client side
        assert!(cfg.proxies[0].listen.is_none());
        assert!(cfg.proxies[0].client_id.is_none());
    }

    #[test]
    fn client_config_without_proxies() {
        // proxies are optional in client mode: internal connection targets are
        // configured on the server admin UI.
        let cfg: ClientConfig = toml::from_str(
            r#"
            client_id = "home-nas"
            server_addr = "example.com:8443"

            [auth]
            token = "secret"

            [tls]
            verify_cert = true
        "#,
        )
        .unwrap();
        assert_eq!(cfg.client_id, "home-nas");
        assert!(cfg.proxies.is_empty());
    }

    #[test]
    fn obfuscation_config_defaults() {
        // Defaults: padding off, padding_max=255, heartbeat_jitter on
        let cfg: ClientConfig = toml::from_str(
            r#"
            client_id = "client-1"
            server_addr = "example.com:8443"

            [auth]
            token = "secret"

            [tls]

            [[proxies]]
            name = "ssh"
            type = "tcp"
            target = "127.0.0.1:22"
        "#,
        )
        .unwrap();
        assert!(!cfg.obfuscation.padding);
        assert_eq!(cfg.obfuscation.padding_max, 255);
        assert!(cfg.obfuscation.heartbeat_jitter);
    }

    #[test]
    fn obfuscation_config_parse() {
        let cfg: ClientConfig = toml::from_str(
            r#"
            client_id = "client-1"
            server_addr = "example.com:8443"

            [auth]
            token = "secret"

            [tls]

            [[proxies]]
            name = "ssh"
            type = "tcp"
            target = "127.0.0.1:22"

            [obfuscation]
            padding = true
            padding_max = 512
            heartbeat_jitter = false
        "#,
        )
        .unwrap();
        assert!(cfg.obfuscation.padding);
        assert_eq!(cfg.obfuscation.padding_max, 512);
        assert!(!cfg.obfuscation.heartbeat_jitter);
    }
}
